openapi: 3.0.0
info:
  title: API de Usuarios
  version: 1.0.0
components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
          description: Nombre del usuario que quiere registrarse
        photo:
          type: string
          description: URL de la foto que el usuario usará como perfil
        email:
          type: string
          description: Email del usuario que quiere registrarse
        password:
          type: string
          description: Contraseña del usuario que quiere registrarse
        role:
          type: number
          description: Para definir los permisos según el rol
      example:
        name: Victoria Navarro
        photo: https://www.mifoto.com/vic.png
        email: vic@greengroceries.com
        password: hola1234
        role: 0
  responses:
    Message200:
      type: object
      properties:
        statusCode:
          type: integer
          format: int64
          description: Codigo de estado correrspondiente a la solicitud al éxito
        message:
          type: string
          description: Texto descriptivo con el éxito en la operación
      example:
        statusCode: 200
        message: Verified User!
    Message201:
      type: object
      properties:
        statusCode:
          type: integer
          format: int64
          description: Codigo de estado correrspondiente a la solicitud al éxito en la creación
        message:
          type: string
          description: Texto descriptivo con el éxito en la creación
      example:
        statusCode: 201
        message: User registered!
    Response200one:
      type: object
      properties:
        statusCode:
          type: integer
          format: int64
          description: Codigo de estado correrspondiente a la solicitud al éxito devolviendo datos
        response:
          type: object
          description: Objeto con los datos del recurso solicitado          
      example:
        statusCode: 200
        response:
          name: Victoria Navarro
          photo: https://www.mifoto.com/vic.png
          email: vic@greengroceries.com
          password: hola1234
          role: 0
    Response200all:
      type: object
      properties:
        statusCode:
          type: integer
          format: int64
          description: Codigo de estado correrspondiente a la solicitud al éxito devolviendo datos
        response:
          type: array
          description: Array de objetos del recurso solicitado
      example:
        statusCode: 200
        response:
          - name: Victoria Navarro
            photo: https://www.mifoto.com/vic.png
            email: vic@greengroceries.com
            password: hola1234
            role: 0
          - name: Matias Zuran
            photo: https://www.mifoto.com/vic.png
            email: MZ@greengroceries.com
            password: hola1243
            role: admin
          - name: Gea Ace
            photo: https://www.mifoto.com/vic.png
            email: GA@greengroceries.com
            password: hola6541
            role: 0
    Paginate:
      type: object
      properties:
        statusCode:
          type: integer
          format: int64
          description: Codigo de estado correrspondiente a la solicitud al éxito devolviendo datos paginados
        response:
          type: array
          description: Array de objetos del recurso solicitado paginados y ordenados
        info:
          type: object
          description: Datos de la paginación
      example:
        statusCode: 200
        response:
          - name: Victoria Navarro
            photo: https://www.mifoto.com/vic.png
            email: vic@greengroceries.com
            password: hola1234
            role: 0
          - name: Matias Zuran
            photo: https://www.mifoto.com/vic.png
            email: MZ@greengroceries.com
            password: hola1243
            role: admin
          - name: Gea Ace
            photo: https://www.mifoto.com/vic.png
            email: GA@greengroceries.com
            password: hola6541
            role: 0
        info:
          next: null
          prev: null
    Error400:
      type: object
      properties:
        statusCode:
          type: integer
          format: int64
          description: Codigo de estado correrspondiente a la solicitud al fracaso por problemas del cliente
        message:
          type: string
          description: Texto descriptivo con mensaje de error por parte del cliente
      example:
        statusCode: 400
        message: Incomplete data on mid
    Error401:
      type: object
      properties:
        statusCode:
          type: integer
          format: int64
          description: Codigo de estado correrspondiente a la solicitud al fracaso de autenticación
        message:
          type: string
          description: Texto descriptivo con mensaje de error de autenticacion
      example:
        statusCode: 401
        message: Bad auth from policies!
    Error403:
      type: object
      properties:
        statusCode:
          type: integer
          format: int64
          description: Codigo de estado correrspondiente a la solicitud al fracaso de autorización
        message:
          type: string
          description: Texto descriptivo con mensaje de error de autorizacion
      example:
        statusCode: 403
        message: Forbidden from policies!
    Error404:
      type: object
      properties:
        statusCode:
          type: integer
          format: int64
          description: Codigo de estado correrspondiente a la solicitud al fracaso por no encontrar lo solocitado
        message:
          type: string
          description: Texto descriptivo con mensaje de error de no encontrado el recurso
      example:
        statusCode: 404
        message: Not found docs
    Error500:
      type: object
      properties:
        statusCode:
          type: integer
          format: int64
          description: Codigo de estado correrspondiente a la solicitud al fracaso por error fatal en el servidor
        message:
          type: string
          description: Texto descriptivo con mensaje de error por parte del servidor
      example:
        statusCode: 500
        message: CODER API ERROR
paths:
  /api/sessions/register:
    post:
      summary: Ruta para el registro de un nuevo usuario en nuestro servidor
      tags:
        - User
      requestBody:
        required: true
        description: Datos para poder registrar un usuario
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        201:
          description: Exito en el registro de un usuario
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Message201'
        400:
          description: Fracaso por datos incompletos o mal pasados
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Error400'
        500:
          description: Fracaso por error fatal en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Error500'
/api/users:
    get:
      summary: Obtener la lista de todos los usuarios, con opción de filtrar por rol
      tags:
        - User
      parameters:
        - name: role
          in: query
          description: Filtro por rol de usuario
          required: false
          schema:
            type: integer
      responses:
        200:
          description: Lista de usuarios obtenida exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Response200all'
        400:
          description: Fracaso por datos incompletos o mal pasados
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Error400'
        500:
          description: Fracaso por error fatal en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/responses/Error500'